language: python
matrix:
	include:
		- python: "2.7"
		  env: TEST_SUITE=suite_2_7 TOX_ENV=py27
		- python: "pypy"
		  env: TEST_SUITE=suite_pypy TOX_ENV=pypy
		- python: "3.4"
		  env: TEST_SUITE=suite_3_4 TOX_ENV=py34
		- python: "3.4"
		  env: TEST_SUITE=suite_3_4 TOX_ENV=pep8

before_install:
  - sudo apt-get install build-essential python-dev

install: pip install tox setuptools virtualenv --upgrade

script: tox -v -e $TOX_ENV -- -v

notifications:
  email:
    - bm_witness@yahoo.com

